---
title: "EDA"
author: "Alexis"
date: "10/7/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
library(tidyverse)
library(viridis)


knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
  )

  options(
    ggplot2.continuous.colour = "viridis",
    ggplot2.continuous.fill = "viridis"
  )
  
  scale_colour_discrete = scale_colour_viridis_d
  scale_fill_discrete = scale_fill_viridis_d
  
  theme_set(theme_minimal() + theme(legend.position = "bottom"))
```
## create the weather data

```{r load_data}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

## 'group_by' and counting

```{r}
weather_df %>%
  group_by(name, month)
```

```{r}
weather_df %>%
  group_by(name) %>%
  summarize(n_obs = n())
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n())
```

```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n_obs = n(),
    n_unique = n_distinct(date))
```

```{r}
weather_df %>%
  count(name)
```

```{r}
weather_df %>%
  count(month)
```

```{r}
weather_df %>%
  count(name, month)
```

Let's make a nice table

```{r}
weather_df %>%
  count(name) %>%
  knitr::kable()
```

## 2x2 tables

```{r}
weather_df %>%
  filter(name != "Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not cold",
      TRUE      ~ ""
    )
  ) %>%
  group_by(name, cold) %>%
  count()
```


```{r}
weather_df %>%
  filter(name != "Waikiki_HA") %>%
  mutate(
    cold = case_when(
      tmax < 5 ~ "cold",
      tmax >= 5 ~ "not cold",
      TRUE      ~ ""
    )
  ) %>%
  janitor::tabyl(name, cold)
```

## general summaries

```{r}
weather_df %>%
  group_by(name) %>%
  summarize(
    n = n(),
    mean_tmax = mean(tmax),
    sd_tmax = sd(tmax),
    median_prcp = median(prcp)
  )
```

```{r}
weather_df %>%
  group_by(name) %>%
  summarize(
    n = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE),
    median_prcp = median(prcp, na.rm = TRUE)
  )
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    n = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE),
    median_prcp = median(prcp, na.rm = TRUE)
  ) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + geom_point() + geom_line()
```

```{r, eval = FALSE}
## this is a check on missing values

weather_df %>%
  filter(is.na(tmax))
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
    ) %>%
  knitr::kable(digits = 1)
```
```

