---
title: "ggplot 1"
author: "Alexis Colangelo"
date: "10/5/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

## Create the weather data

```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"),
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Create a ggplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point()

```

## Alternate way of making this plot
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

```

saving initial plots

```{r}
scatterplot = weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point()

scatterplot
```

adding color:

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point(aes(color = name))
```

adding transparency:

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point(aes(color = name), alpha = .4)
```

this
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) + geom_point(aes(color = name), alpha = .4) + geom_smooth(se = FALSE)
```
vs.
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) + geom_point(alpha = .4) + geom_smooth(se = FALSE)
```