---
title: "ggplot 2"
author: "Alexis Colangelo"
date: "10/6/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
library(patchwork)
```

## Create the weather data

```{r load_data, cache = TRUE}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"),
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## making new plots

start with an old plot
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

add labels:
```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnoaa package"
  )
```

x axis tick marks etc

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnoaa package"
  ) +
  scale_x_continuous(
    breaks = c(-15, -5, 20),
    labels = c("-15C", "-5C", "20C")
  )
```

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnoaa package"
  ) +
  scale_x_continuous(
    breaks = c(-15, -5, 20),
    labels = c("-15C", "-5C", "20C") +
      scale_y_continuous(
        trans = "sqrt"
      )
  )
```

## colors

```{r}
weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnoaa package"
  ) +
  scale_color_hue(
    name = "Weather Station",
    h = c(50, 250)
  )
```

```{r}
ggp_base = 
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum Temp (C)",
    y = "Maximum Temp (C)",
    caption = "Data from NOAA via rnoaa package"
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )
```

## themes

```{r}
ggp_base +
  theme(legend.position = "bottom")
```

```{r}
ggp_base +
  theme_bw() +
  theme(legend.position = "bottom")
```

```{r}
ggp_base +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
ggp_base +
  theme_minimal() +
  theme(legend.position = "none")
```

where does warning message: removed 15 rows containing missing values come from?

Because no tmin (x axis) values for 15 observations
```{r}
weather_df %>%
  filter(is.na(tmin))
```

## more than one dataset

```{r}
central_park =
  weather_df %>%
  filter(name == "CentralPark_NY")

waikiki =
  weather_df %>%
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + geom_point()
```

```{r}
ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point() +
  geom_line(data = central_park)
```

```{r}
ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp)) +
  geom_line(data = central_park)
```

(brief aside about colors): have to specify color inside the geom that corresponds to it

```{r}
waikiki %>%
  ggplot(aes(x = date, y = tmax)) +
  geom_point(color = "blue")
```

## Multi-panel plots

```{r}
ggp_scatter =
  weather_df %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_scatter 

ggp_density =
  weather_df %>% 
  ggplot(aes(x = tmin)) +
  geom_density()

ggp_density

ggp_box =
  weather_df %>%
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

ggp_box

ggp_scatter + ggp_density

(ggp_scatter + ggp_density) / ggp_box
```




